### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by cbetta** [interfax/contributor-instructions#3]
@if-adam is there a test environment developers of these libraries can use?

**Comment by UPIF-Marketing** [comment]
Do you mean a registration-less environment? If so, no.

Otherwise, it's simply their developer account.

**Comment by cbetta** [comment]
@if-adam can you describe the best practices for someone to test the following:
1. How to test sending a fax without actually having a fax to send anything to?
2. How to test receiving a fax without actually having a fax to send from?

I'm asking because we can not assume the developers for the libraries have faxes.

**Comment by UPIF-Marketing** [comment]
> How to test sending a fax without actually having a fax to send anything to?

Based on your DX feedback, we're setting up a method of faxing that won't require having a fax number, so there's a current answer to this question and a longer-term one.

**For the moment**, the developer has no choice but to fax to the number he provided upon registration, otherwise his API call will be immediately rejected on error [-111 _Attempting to fax to a number that is not the designated fax number in a developer account._](https://www.interfax.net/en/dev/webservice/reference/web-service-return-codes).

Assuming he doesn't have a fax number at all and that he provided some dummy number upon registration, he can "fax" to that dummy number, which will eventually fail as a fax, but which will still leave an outbound record in his outbound queue. The status of such a fax can be validly queried both during transmission and after completion.

If the dummy number he provided is some random junk which he can't remember, he'll need to contact us to change that number to something memorable. We can then set the designated fax number to something that will consistently fail, or provide him with an inbound number to which he can fax. The latter is a manual process, but we do this happily.

**Over the longer term**, one possible solution we're looking at is to accommodate reserved dummy numbers. For example, faxing to +999-99-999-9999 would, firstly, be accepted by the API, regardless of what the developer's actual designated fax number is. Secondly, it would  always yield a faxing [status code](https://www.interfax.net/en/help/error_codes) of '0:success', while faxing to +999-99-999-nnnn would yield a status code of nnnn.

> How to test receiving a fax without actually having a fax to send from?

We need to take a step back here, and remember that the developer API is primarily intended for outbound testing. This is an unfortunate result of having to protect ourselves from allowing developer accounts to be abused to get free inbound service.

Having said that, and as I mentioned above, if developers make the effort to contact us for an inbound number, we accommodate them and provide it.

That's when your question comes into play. At this point I'd say they can either use the API to send themselves a fax or use our email-to-fax interface to send themselves a fax.

**Comment by cbetta** [comment]
@if-adam let me clarify the scope here. How do we let the devs for the new libraries test if their library works correctly. This is the `contributor-instructions` doc afterall :)

**Comment by cbetta** [comment]
As for dummy numbers: I love it. One extra idea here: it would be cool if you have a set of numbers that all return different statuses.  E.g the number ending on 0 returns status 0, etc. This can be handy for people to test not just success but also errors.
